[build]
  base = "potfolio"
  command = "npm install --include=dev && npm run build && echo '--- FILE LISTING ---' && ls -R dist || echo 'dist not found'"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  VITE_STATIC_EXPORT = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
